services:
  mysql:
    image: mysql:latest

    restart: always

    container_name: mysql-container

    ports:
      - 3306:3306

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: "Asia/Seoul"

    volumes:
      - db:/var/lib/mysql
      - ./app/src/config/db:/docker-entrypoint-initdb.d

    networks:
      - my-network

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  server:
    build:
      context: ./app
      dockerfile: Dockerfile

    restart: always

    env_file:
      - .env

    container_name: server-container

    ports:
      - "3000:3000"

    depends_on:
      - mysql

    volumes:
      - ./app:/usr/src/app
      - node_modules:/usr/src/app/node_modules

    networks:
      - my-network

volumes:
  db:
  node_modules:


networks:
  my-network:
    driver: bridge
